import Head from 'next/head';
import Header from '../header';
import Footer from '../footer';
import { Container, Row, Col } from "react-grid-system";

export default function Layout({children}) {
    return (
      <>
        <Head>
          <title key='title'>
            The portfolio of Jonathan &quot;ThatGuyJK&quot; Kelly
          </title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <Header />
        <Container fluid>
          <Row>
            <Col xs={12}>
              <main>{children}</main>
            </Col>
          </Row>
        </Container>
        <Footer />
      </>
    );
};
