import {useState, useEffect} from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { getFeaturedProjects } from "../lib/api";
import styles from '../styles/Home.module.scss'

export default function Home({featuredProjects}) {
  const [featured, setFeatured] = useState([]);

  useEffect(() => {
    setFeatured(featuredProjects);
    console.log('featured', featuredProjects);
  }, [featuredProjects]);

  const FeaturedProject = ({details}) => {
    return  (
      <div style={{
        color: '#ffffff',
        background: details.fields.primaryColor
      }}>
        <Link href={'projects/'+details.fields.slug}>{details.fields.title}</Link>
      </div>
    )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title key='title'>The portfolio of Jonathan &quot;ThatGuyJK&quot; Kelly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          { featured.map((prj, index) => {
              return (
                <FeaturedProject details={prj} key={index} />
              );
            }) 
          }
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const featuredProjects = await getFeaturedProjects();

  return {
    props: {
      featuredProjects,
    },
  };
}
